### PR TITLE
closes #127

### LINKED ISSUE #127: add-extension fails for type mapping_provider with no extras
* Release number or git hash: 2873fbbb629aae8bd30c3591e6fc1ff83fceb818
* OS: ubuntu 17.10

### Steps to reproduce

1. create a server plugin
2. yo phovea:add-extension

- Type mapping_provider
- ID someId
- File Name someFileName
- Extras: none

### Observed behavior
* Any unexpected output or action (or lack of expected output or action)
* Static or animated images showing the UI behavior

```code
node_modules/generator-phovea/generators/add-extension/templates/mapping_provider.tmpl.py:7
    5|
    6|
 >> 7| class <%-moduleName%>Table(object):
    8|   def __init__(self):
    9|     self.from_idtype = 'TODO'
    10|     self.to_idtype = 'TODO'

moduleName is not defined
```

### Expected behavior
* create extension

### PR DESCRIPTION
**Pull request by lehnerchristian**
closes #127

### CODE REVIEW

File: generators/add-extension/index.js [hunk 1]
```diff
@@ -132,7 +132,9 @@ class Generator extends Base {
       if (!this.fs.exists(source)) {
         source = this.templatePath('template.tmpl.py');
       }
-      this.fs.copyTpl(source, target, d);
+      this.fs.copyTpl(source, target, Object.assign({
```
Comment (sgratzl) [inline generators/add-extension/index.js]: please extract the enhanced config argument to an object since it is now defined twice, once for web and once for the server. Next time I will again forget it to change.
